version: 2.1
jobs:
  build: &build
    docker:
      - image: fpco/stack-build:lts
    environment:
      STACK_YAML: stack.yaml
    steps:
      - checkout
      - run:
          name: Dump STACK_YAML
          command: cat $STACK_YAML > stack_yaml_contents
      - restore_cache:
          name: Restore cache
          key: reddit-{{ checksum "package.yaml" }}-{{ checksum "stack_yaml_contents" }}
      - run:
          name: Setup
          command: stack setup
      - run:
          name: Test
          command: stack test
      - restore_cache:
          name: Save cache
          key: reddit-{{ checksum "package.yaml" }}-{{ checksum "stack_yaml_contents" }}
          paths:
            - ~/.stack
            - ~/.stack-work
  build-nightly:
    <<: *build
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          key: reddit-nightly-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Set
          command: stack setup --resolver=nightly
      - run:
          name: Test
          command: stack test --resolver=nightly
      - restore_cache:
          name: Save cache
          key: reddit-nightly-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ~/.stack-work
  lts-19-15-build:
    <<: *build
    environment:
      STACK_YAML: stack-lts-19.15.yaml

workflows:
  version: 2
  everything:
    jobs:
      - build
      - build-nightly
      - lts-19-15-build
  nightly:
    triggers:
      - schedule:
          cron: "0 18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-nightly
